name: survey_app_synapsis
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  card_swiper: ^3.0.1
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  intl: ^0.18.1
  lottie: ^2.7.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  phosphor_flutter: ^2.0.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
